import Link from "next/link";
import { getShared, isShareConfigured } from "@/lib/store";
import { ResultView } from "@/components/ResultView";
import type { ResearchResult } from "@/lib/agent";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type SharedPayload = { result: ResearchResult; savedAt: number; queryId: string };

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  if (!isShareConfigured()) return { title: "Sebutkan — shared research" };
  const data = await getShared<SharedPayload>(id).catch(() => null);
  const q = data?.result.query;
  return {
    title: q ? `${q.slice(0, 60)} — Sebutkan` : "Sebutkan — shared research",
    description: data?.result.summary?.slice(0, 160) ?? "An AI research agent that cites and pays its sources.",
  };
}

export default async function SharedResultPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;

  if (!isShareConfigured()) {
    return (
      <Shell>
        <p className="text-sm text-[var(--muted)]">
          Public sharing isn’t configured on this deployment. The author can still re-open this run from
          their own device (Research → Recent research).
        </p>
      </Shell>
    );
  }

  const data = await getShared<SharedPayload>(id).catch(() => null);
  if (!data) {
    return (
      <Shell>
        <h1 className="serif text-2xl font-semibold">Not found</h1>
        <p className="mt-2 text-sm text-[var(--muted)]">
          This shared result has expired or never existed.{" "}
          <Link href="/dashboard/research" className="link-accent underline">
            Run your own →
          </Link>
        </p>
      </Shell>
    );
  }

  const { result, savedAt, queryId } = data;

  return (
    <Shell>
      <p className="text-[11px] uppercase tracking-[0.15em] text-[var(--accent)]">Shared research</p>
      <h1 className="serif mt-1 text-3xl font-semibold tracking-tight">{result.query}</h1>
      <p className="mt-1 text-[11px] text-[var(--muted)]">
        Saved {new Date(savedAt).toUTCString()} ·{" "}
        {result.confidence ? `confidence: ${result.confidence} · ` : ""}
        {result.rounds && result.rounds > 1 ? `${result.rounds} rounds · ` : ""}
        <Link href="/dashboard/activity" className="link-accent underline" title={queryId}>
          on-chain attestation ↗
        </Link>
      </p>

      <div className="mt-6">
        <ResultView result={result} />
      </div>

      <footer className="mt-10 flex items-center justify-between border-t border-[var(--rule)] pt-4 text-[11px] text-[var(--muted)]">
        <span>
          Generated by{" "}
          <Link href="/" className="link-accent font-medium underline">
            Sebutkan
          </Link>{" "}
          — the research agent that cites <em>and pays</em> its sources.
        </span>
        <Link href="/dashboard/research" className="rounded-md bg-[var(--accent)] px-3 py-1.5 font-medium text-white">
          Run your own →
        </Link>
      </footer>
    </Shell>
  );
}

function Shell({ children }: { children: React.ReactNode }) {
  return (
    <main className="min-h-dvh bg-[var(--paper)]">
      <div className="mx-auto w-full max-w-3xl px-6 py-12">{children}</div>
    </main>
  );
}
